name: Run-DocToc
on:
  push:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  generateTOC:
    name: Generate-TOC
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
  
